# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xKAN',
                'doc_host': 'https://mlsquare.github.io',
                'git_url': 'https://github.com/mlsquare/xKAN',
                'lib_path': 'xKAN'},
  'syms': {'xKAN.core': {'xKAN.core.foo': ('core.html#foo', 'xKAN/core.py')}}}
